version: "3.6"

services:
  frontend: 
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV=development
      - NODE_PATH=src